---
root: true
extends: ['@cherryblossom/eslint-config/node']
ignorePatterns: [dist/]

overrides:
- files: [tests/**/*.test.ts]
  env:
    jest: true
- files: [scripts/**/*]
  rules:
    node/no-process-exit: 0
    node/no-unpublished-import: 0
- files: [src/commands/*, src/regex-commands/*]
  rules:
    import/no-unused-modules: 0

rules:
  jsdoc/check-param-names: 0
  jsdoc/newline-after-description: 0
  jsdoc/require-param: 0
  jsdoc/require-returns: 0
