root: true
extends: ['@cherryblossom/eslint-config/node']
ignorePatterns:
- .history/
- dist/
- tests/coverage
overrides:
- files: ['**/jest.config*.js']
  rules:
    jsdoc/valid-types: 0
    node/no-unpublished-require: 0
- files:
  - scripts/**
  - packages/*/scripts/**
  rules:
    node/no-extraneous-import: 0
    node/no-process-exit: 0
    node/no-unpublished-import: 0
