language: node_js
node_js: v12.16.1
branches:
  except: repl
before_install: npm i -g pnpm@5
install: pnpm i
jobs:
  script:
  - pnpm -C packages/commitlint-plugin build
  - pnpx commitlint-travis
  - pnpm build
  - pnpm lint
  - pnpm test
  after_success: chmod +x scripts/push-docs.sh && scripts/push-docs.sh
  deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x scripts/deploy.sh && scripts/deploy.sh
    on: main
