language: node_js
node_js: lts/*
branches:
  except: repl
before_install: npm i -g pnpm
install:
- pnpm i
jobs:
  script:
  - pnpm typecheck
  - pnpm build
  - pnpm lint
  - pnpm test
  after_success: chmod +x scripts/push-docs.sh && scripts/push-docs.sh
  deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x scripts/deploy.sh && scripts/deploy.sh
    on: master
