language: node_js
node_js: lts/*
before_install: npm i -g pnpm
install:
  - pnpm i
jobs:
    script:
      - pnpm run build
      - pnpm run lint
      - pnpm run test
      - pnpm run docs
    after_success: chmod +x scripts/push-docs.sh && scripts/push-docs.sh
    deploy:
      - provider: script
        skip_cleanup: true
        script: pnpx semantic-release
        on: master
