blank_issues_enabled: false
contact_links:
- name: Discussions
  url: https://github.com/cherryblossom000/comrade-pingu/discussions/new
  about: Please ask questions about the bot or just discuss it in general here.
