extends: ['plugin:@comrade-pingu/recommended']
plugins: ['@comrade-pingu']
ignorePatterns:
- dist/
- tests/coverage

overrides:
- files:
  - src/commands/*.ts
  - src/regex-commands/*.ts
  - src/events/*.ts
  rules:
    import/no-unused-modules: 0
- files: [tests/**/*.test.ts]
  env:
    jest: true

rules:
  jsdoc/check-param-names: 0
  jsdoc/newline-after-description: 0
  jsdoc/require-param: 0
  jsdoc/require-throws: 0
  jsdoc/require-returns: 0
