extends: plugin:@comrade-pingu/recommended
plugins: ['@comrade-pingu']
ignorePatterns: [tests/coverage/]
rules:
  jsdoc/check-param-names: 0
  jsdoc/newline-after-description: 0
  jsdoc/require-param: 0
  jsdoc/require-throws: 0
  jsdoc/require-returns: 0
  # Just for types
  node/no-unpublished-import:
  - 2
  - allowModules:
    - discord-api-types
    - mathjax-full
    - type-fest
