rules:
  # Only for types
  node/no-extraneous-import:
  - 2
  - allowModules: [semantic-release]
  node/no-unpublished-import:
  - 2
  - allowModules:
    - '@octokit/rest'
    - type-fest

overrides:
- files: [src/index.ts]
  rules:
    # Main file
    import/no-unused-modules: 0
- files: [src/*.d.ts]
  rules:
    # Have to import multiple times for different module declarations
    import/no-duplicates: 0
    # Typing a module, import can't detect it
    import/no-unused-modules: 0
