name: CI
on:
  push:
    branches-ignore: [repl]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.4.0
      with:
        node-version: 16

    - name: Cache pnpm modules
      uses: actions/cache@v2.1.6
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.14.7
        run_install: true

    - name: Build
      run: pnpm build
    - name: Lint
      run: pnpm lint
    - name: Test
      run: pnpm test
    - name: Update docs
      run: scripts/push-docs.sh
      env:
        GIT_AUTHOR_NAME: Github Actions
        GIT_COMMITTER_NAME: Github Actions
        GIT_AUTHOR_EMAIL: actions@github.com
        GIT_COMMITTER_EMAIL: actions@github.com

    - name: Upload build data
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-data
        path: |
          scripts/dist
          packages/bot/dist
        if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    env:
      GIT_COMMITTER_NAME: cherryblossom
      GIT_COMMITTER_EMAIL: 31467609+cherryblossom000@users.noreply.github.com

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.4.0
      with:
        node-version: 16

    - uses: crazy-max/ghaction-import-gpg@v3.2.0
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git-user-signingkey: true
        git-commit-gpgsign: true

    - name: Cache pnpm modules
      uses: actions/cache@v2.1.6
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.14.7
        run_install: true

    - name: Download build data
      uses: actions/download-artifact@v2.0.10
      with:
        name: build-data

    - name: Release
      run: pnpx multi-semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      run: scripts/deploy.sh
      env:
        GIT_AUTHOR_NAME: Github Actions
        GIT_COMMITTER_NAME: Github Actions
        GIT_AUTHOR_EMAIL: actions@github.com
        GIT_COMMITTER_EMAIL: actions@github.com
